"""init

Revision ID: 8947b350033c
Revises: 
Create Date: 2026-02-03 13:19:15.549000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8947b350033c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分类id'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户邮箱'),
    sa.Column('password', sa.String(length=200), nullable=False, comment='用户密码（加密）'),
    sa.Column('role', sa.Enum('BUYER', 'SELLER', name='userrole'), nullable=False, comment='用户角色：buyer（购买者）/seller（商家）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品id'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='商品标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='商品描述'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='商品分类表id'),
    sa.Column('price', sa.Integer(), nullable=False, comment='商品价格，单位：分'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='商品库存'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='用于业务状态控制：草稿draft、上架active、下架inactive、缺货out_of_stock'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='商品所属商家id'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_products_seller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_index(op.f('ix_products_updated_at'), 'products', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_updated_at'), table_name='products')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
