"""init

Revision ID: 1d07fba01fd2
Revises: 
Create Date: 2026-02-03 13:19:43.296666

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d07fba01fd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_vector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='原始商品id'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='商家id'),
    sa.Column('content', sa.Text(), nullable=False, comment='商品描述块'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='描述文本块在原文的顺序索引'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='商品标题'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False, comment='向量数据'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='同步时间，用于增量更新判断'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_vector'))
    )
    op.create_index('idx_product_category', 'product_vector', ['product_id', 'category'], unique=False)
    op.create_index(op.f('ix_product_vector_product_id'), 'product_vector', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_vector_seller_id'), 'product_vector', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_vector_seller_id'), table_name='product_vector')
    op.drop_index(op.f('ix_product_vector_product_id'), table_name='product_vector')
    op.drop_index('idx_product_category', table_name='product_vector')
    op.drop_table('product_vector')
    # ### end Alembic commands ###
